### ISSUE TITLE
AttributeError: module 'pyflex' has no attribute 'init'

### ISSUE THREAD

**Issue by SA-GIMA** [dengyh16code/language_deformable#1]
When generating initial configurations, an error message was encountered as follows:

$ python generate_configs.py --cloth_type Square
Traceback (most recent call last):
  File "/home/sjh/project/language_deformable/generate_configs.py", line 188, in <module>
    pyflex.init(True, True, 720, 720)
    ^^^^^^^^^^^
AttributeError: module 'pyflex' has no attribute 'init'

 The pyflex plugin was installed using the pip install pyflex command, and it is not clear if there are any issues 

您好，我在生成初始配置 时，遇到问题报错如上，其中pyflex是通过pip install pyflex指令安装的，并不清楚问题出在了哪里

**Comment by dengyh16code** [comment]
hello, i'm still organizing my code, so maybe there are some bugs. if the bugs are related to softgym and simulation. you can follow this blog: https://danieltakeshi.github.io/2021/02/20/softgym/

**Comment by dengyh16code** [comment]
by the way, have you set up the paths as my suggestion?

**Comment by SA-GIMA** [comment]
> by the way, have you set up the paths as my suggestion?

Of course, I have already executed the set up the paths command

**Comment by SA-GIMA** [comment]
> hello, i'm still organizing my code, so maybe there are some bugs. if the bugs are related to softgym and simulation. you can follow this blog: https://danieltakeshi.github.io/2021/02/20/softgym/

If it's convenient, could you please share the requirements. txt file so that we can install the correct version of the library? Alternatively, you can directly share the anaconda environment, which will be simpler.如果方便的话，可以麻烦您分享一下requirements.txt文件，以方便我们安装正确版本的库，或者可以直接分享anaconda环境，这样会更简单。

**Comment by dengyh16code** [comment]
i have tested the repo. it works well. Your problem of pyflex is related to softgym, not my repo. After you set up the softgym environment well, you can use my repo according to the instructions in the readme.md.
